// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EmployeeDetailS.Entity
{
    public partial class EmployeeDetails
    {
        [Key]
        public int Employee_Id { get; set; }
        [Required]
        [StringLength(30)]
        public string FullName { get; set; }
        [Required]
        [StringLength(20)]
        public string Username { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        public int Department { get; set; }
        [Required]
        [StringLength(20)]
        public string Marticule { get; set; }
        [Required]
        [StringLength(50)]
        public string Address { get; set; }
        public long PhoneNumber { get; set; }
        [Required]
        [StringLength(20)]
        public string Gender { get; set; }
        public bool Is_Deleted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created_Time_Stamp { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated_Time_Stamp { get; set; }
    }
}